# Generated by Django 5.1.6 on 2025-03-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'Passport'), ('VOTERS_CARD', "Voter's Card")], max_length=20)),
                ('document_front', models.ImageField(help_text='Front side of your ID document', upload_to='kyc_documents/')),
                ('document_back', models.ImageField(help_text='Back side of your ID document', upload_to='kyc_documents/')),
                ('selfie_with_id', models.ImageField(help_text='Selfie while holding your ID', upload_to='kyc_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date when KYC was verified', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if KYC was rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
        migrations.CreateModel(
            name='WorkerAdditionalKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_clearance', models.FileField(help_text='Police clearance certificate', upload_to='worker_documents/')),
                ('proof_of_address', models.FileField(help_text='Utility bill or lease agreement', upload_to='worker_documents/')),
                ('reference_letter', models.FileField(blank=True, help_text='Letter of recommendation (optional)', null=True, upload_to='worker_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_additional', to='KYC.kycverification')),
            ],
            options={
                'verbose_name': 'Worker Additional KYC',
                'verbose_name_plural': 'Worker Additional KYCs',
            },
        ),
    ]
