# Generated by Django 5.1.6 on 2025-03-09 02:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('idType', models.CharField(choices=[('DL', "Driver's License"), ('PP', 'International Passport'), ('VC', "Voter's Card"), ('NI', 'National ID')], default='PP', max_length=2)),
                ('idNumber', models.CharField(max_length=50)),
                ('idDocument', models.ImageField(help_text='Upload a clear image of your ID document', upload_to='ID')),
                ('selfieImage', models.ImageField(help_text='Take a clear selfie in good lighting', upload_to='selfie')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INCOMPLETE', 'Incomplete Documentation')], default='PENDING', max_length=10)),
                ('verificationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'indexes': [models.Index(fields=['status', 'verificationDate'], name='KYC_kycveri_status_d33c7d_idx'), models.Index(fields=['user', 'status'], name='KYC_kycveri_user_id_bf286a_idx')],
            },
        ),
    ]
