# Generated by Django 5.1.6 on 2025-03-09 00:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KYC', '0002_remove_workeradditionalkyc_kyc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('idType', models.CharField(choices=[('DL', "Driver's License"), ('PP', 'International Passport'), ('VC', "Voter's Card"), ('NI', 'National ID')], default='PP', max_length=2)),
                ('idNumber', models.CharField(max_length=50)),
                ('idDocument', models.ImageField(upload_to='kyc/id_documents/')),
                ('selfieImage', models.ImageField(upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verificationDate', models.DateTimeField(auto_now_add=True)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('nameSimilarityScore', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('faceSimilarityScore', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
    ]
