# Generated by Django 5.1.6 on 2025-03-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='faceSimilarityScore',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='idExpiryDate',
            field=models.DateField(blank=True, help_text='ID document expiry date', null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reviewFlag',
            field=models.CharField(blank=True, choices=[('NAME_MISMATCH', 'Name Mismatch'), ('AGE_VERIFICATION', 'Age Verification Needed'), ('ID_UNCLEAR', 'ID Document Unclear'), ('SELFIE_MISMATCH', 'Selfie Mismatch'), ('EXPIRED_ID', 'Expired ID Document'), ('OTHER', 'Other Issues')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reviewNotes',
            field=models.TextField(blank=True, help_text='Internal notes for review process', null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reviewedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='idDocument',
            field=models.ImageField(help_text='Upload a clear image of your ID document', upload_to='kyc/id_documents/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfieImage',
            field=models.ImageField(help_text='Take a clear selfie in good lighting', upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INCOMPLETE', 'Incomplete Documentation')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status', 'verificationDate'], name='KYC_kycveri_status_d33c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['user', 'status'], name='KYC_kycveri_user_id_bf286a_idx'),
        ),
    ]
