# Generated by Django 5.1.6 on 2025-03-23 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0003_alter_kycverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='idDocument',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_type'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfieImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selfie'),
        ),
    ]
