# Generated by Django 5.1.6 on 2025-03-18 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food'), ('other', 'Other')], max_length=20)),
                ('fragile', models.BooleanField(default=False)),
                ('specialInstructions', models.TextField(blank=True)),
                ('pickupAddress', models.CharField(max_length=255)),
                ('pickupLg', models.CharField(max_length=200)),
                ('pickupCity', models.CharField(max_length=100)),
                ('pickupState', models.CharField(max_length=100)),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('pickupContactName', models.CharField(max_length=100)),
                ('pickupContactPhone', models.CharField(max_length=15)),
                ('pickupInstructions', models.TextField(blank=True)),
                ('deliveryAddress', models.CharField(max_length=255)),
                ('deliveryCity', models.CharField(max_length=100)),
                ('deliveryState', models.CharField(max_length=100)),
                ('recipientName', models.CharField(max_length=100)),
                ('recipientPhone', models.CharField(max_length=15)),
                ('recipientEmail', models.EmailField(blank=True, max_length=254)),
                ('deliveryInstructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
