# Generated by Django 5.1.6 on 2025-03-18 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='itemImage',
            field=models.ImageField(blank=True, default='default_delivery.png', null=True, upload_to='delivery_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'heic'])]),
        ),
    ]
