# Generated by Django 5.1.6 on 2025-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swift', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='_last_read',
            field=models.TextField(db_column='last_read', default='{}'),
        ),
    ]
