# Generated by Django 5.1.6 on 2025-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swift', '0005_delivery__last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
