# Generated by Django 5.1.6 on 2025-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swift', '0006_delivery_current_latitude_delivery_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='transit_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
