# Generated by Django 5.1.6 on 2025-03-23 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Swift', '0009_delivery_paid_at_delivery_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_image'),
        ),
    ]
