# Generated by Django 5.1.6 on 2025-03-09 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('WORKER', 'Worker')], max_length=20)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('taxId', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('cacNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('contactName', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('fleetSize', models.IntegerField(blank=True, null=True)),
                ('fleetType', models.CharField(blank=True, max_length=200, null=True)),
                ('businessLicense', models.ImageField(blank=True, null=True, upload_to='business_licenses/')),
                ('insuranceCert', models.ImageField(blank=True, null=True, upload_to='insurance_certificates/')),
                ('cacCertificate', models.ImageField(blank=True, null=True, upload_to='cac_certificates/')),
                ('taxClearance', models.ImageField(blank=True, null=True, upload_to='tax_clearance/')),
                ('kyc_status', models.BooleanField(default=False)),
                ('is_user_verified', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_pending_deletion', models.BooleanField(default=False)),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'COMPANY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
