# Generated by Django 5.1.6 on 2025-03-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profileimage',
        ),
    ]
