# Generated by Django 5.1.6 on 2025-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='localGovernment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
