# Generated by Django 5.1.6 on 2025-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_driverslicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driversLicense',
            field=models.ImageField(blank=True, default='', null=True, upload_to='License'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='localGovernment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehiclePlateNumber',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehicleRegistration',
            field=models.ImageField(blank=True, default='', null=True, upload_to='vehicleReg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehicleType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
