# Generated by Django 5.1.6 on 2025-03-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_customuser_driverslicense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vehiclePlateNumber',
        ),
    ]
