# Generated by Django 5.1.6 on 2025-03-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_bus_license_customuser_businesslicense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fleetSize',
        ),
    ]
