# Generated by Django 5.1.6 on 2025-03-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_customuser_vehicleplatenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vehiclePlateNumber',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
