# Generated by Django 5.1.6 on 2025-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_customuser_vehicleplatenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
