# Generated by Django 5.1.6 on 2025-03-23 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_customuser_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='businessLicense',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cacCertificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='driversLicense',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='driver/licence'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='insuranceCert',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='insurance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxClearance',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehicleRegistration',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='registration'),
        ),
    ]
