# Generated by Django 5.1.6 on 2025-03-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_customuser_fleetsize'),
        ('Auth', '0007_remove_customuser_dob_remove_customuser_firstname_and_more'),
    ]

    operations = [
    ]
